
### PETICIONES GET, POST, PUT, DELETE DE LA TABLA EMPLEADOS ###

GET http://localhost:3000/api/employees

###

POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "nombre": "Prueba",
    "dni": "8324392",
    "sexo": "m",
    "fecha_nac": "1974-04-03",
    "salario": "1200",
    "cargo": "contable",
    "jefe_id": 2
}

###
PUT http://localhost:3000/api/employees
Content-Type: application/json

{
    "id": 11,
    "nombre": "Prueba PARA BORRAR",
    "dni": "2762",
    "sexo": "m",
    "fecha_nac": "1979-04-08",
    "salario": "1200",
    "cargo": "contable",
    "jefe_id": 2
}

###
DELETE http://localhost:3000/api/employees
Content-Type: application/json

{
    "id": 11
}


### PETICIONES GET, POST, PUT, DELETE DE LA TABLA DEPARTAMENTOS ###

###
GET http://localhost:3000/api/departments